### ISSUE TITLE
Splits not clear

### ISSUE THREAD

**Issue by zackhsi** [joshdick/airline-onedark.vim#1]
You've been awesome thus far... I have one last annoyance :)

The split color is the same as the background, making it hard to see where one starts and the other one ends.

<img width="566" alt="screen shot 2016-04-15 at 4 09 58 pm" src="https://cloud.githubusercontent.com/assets/806101/14577109/84e8043e-0324-11e6-8534-96f17e5efd4a.png">

**Comment by joshdick** [comment]
You're using Airline? Do you have the status car disabled for spits?

**Comment by zackhsi** [comment]
https://github.com/zackhsi/dotfiles/blob/75dc4457119c5e9038bc8163717b7b7f3f70ef35/sources/vimrc#L150-L157

**Comment by zackhsi** [comment]
It's enabled. It's just that the background color is the same as the tabline color.

**Comment by joshdick** [comment]
Gotcha. Ran out of time to look at this right now, but I'll get to it sometime this weekend.

**Comment by zackhsi** [comment]
:+1: thanks!

**Comment by joshdick** [comment]
I think I was confused because the right side of your screenshot is cut off; do you still see the right side of the Airline status bar when using the "airline-onedark" theme? This has been enough of a visual indicator of the split for me, but I can still experiment with changing the background color.

**Comment by joshdick** [comment]
I found something that I think works well. :)

**Comment by zackhsi** [comment]
You, sir, are excellent.
